#!/bin/bash

creategitconfig() {
	
	local GITEMAIL=$(grep -v '^:' user-info | cut -d ':' -f2 | sed -n '1p')
	local GITNAME=$(grep -v '^:' user-info | cut -d ':' -f2 | sed -n '2p')
	
	rm -r ~/.gitconfig 2>/dev/null || true
	
	git config --global init.defaultBranch main
	git config --global user.name "$GITNAME"
	git config --global user.email "$GITEMAIL"
}

installapps() {

    local INPUTFILE=apps

    echo "You are running the script as root"
    echo ""

    if [ $(id -u) == "0" ]
    then
        echo "Updating local repository ..."
        echo ""
        echo ""
        apt update
        apt list --upgradable
        apt upgrade 

        echo ""
        echo ""
        echo "Installing apps ..."
        echo ""
        echo ""
        
        while read -r LINE
        do
            apt install --no-install-recommends -y $LINE
        done < "$INPUTFILE"
    else
        echo "You are running the script as local"
        echo "Use the command <su root -- -c 'bash dotinstall -g'> or <su root -- -c 'bash dotinstall --getapps'>."
    fi
}

checkapps() {
    
    declare -a PKGS=(git i3 i3status xdotool xclip dunst yad dmenu mat2 exiftool qpdf rofi xwallpaper) 
    declare -i SUMPKGS=0

    for i in "${PKGS[@]}";do
        CHECK=$(command -v "$i")

        if [[ $? -eq 0 ]]; then
            SUMPKGS+=1
            echo "$i is installed"
        fi
    done

    echo ""

    if [[ $SUMPKGS -ne ${#PKGS[@]} ]]
    then
        echo "Necessary packages are not installed."
        echo "Use the command <su root -- -c 'bash dotinstall -g'> or <su root -- -c 'bash dotinstall --getapps'>."
        exit
    else
        echo "Necessary packages are installed."
    fi
}

installdotfiles() {

    checkapps

    echo "Installing dotfiles in your system..."
	
	local BASEDIR=$(dirname $0)
	cd $BASEDIR
	
	local I3DIR=${PWD}/config/i3
	local I3=$HOME/.config/i3
	local I3STATUSDIR=${PWD}/config/i3status
	local I3STATUS=$HOME/.config/i3status
	local WALLPAPERFILE=${PWD}/local/share/abstract.png
	local WALLPAPER=$HOME/.local/share/wallpaper
	local SCRIPTSDIR=${PWD}/local/scripts
	local SCRIPTS=$HOME/.local/scripts
    
	[[ -d $I3 ]] && rm -r $I3 2>/dev/null || true
	[[ -d $I3STATUS ]] && rm -r $I3STATUS 2>/dev/null || true
	[[ -d $SCRIPTS ]] && rm -r $SCRIPTS 2>/dev/null || true
	[[ -f $WALLPAPERFILE ]] && rm $WALLPAPER 2>/dev/null || true

	ln -sd $I3DIR $I3 2>/dev/null || true
	ln -sd $I3STATUSDIR $I3STATUS 2>/dev/null || true
	ln -sd $SCRIPTSDIR $SCRIPTS 2>/dev/null || true
	ln -sf $WALLPAPERFILE $WALLPAPER 2>/dev/null || true
	
	creategitconfig
    
	xdotool key Super_L+Shift_R+r
}

uninstalldotfiles() {
	
	echo "Uninstall dotfiles ..."
	
	rm -r ~/.config/i3 2>/dev/null || true
	rm -r ~/.config/i3status 2>/dev/null || true
	rm -r ~/.local/scripts 2>/dev/null || true
	rm -r ~/.local/share/wallpaper 2>/dev/null || true
	rm -r ~/.gitconfig 2>/dev/null || true
	i3-config-wizard
}

case $1 in
	-i | --install)
		installdotfiles
	;;
	-u | --uninstall)
		uninstalldotfiles
	;;
    -g | --getapps)
        installapps
    ;;
	*)
		echo "No option"
	;;
esac
